
test('our first test', ()=>{
    throw new Error('something failed')
})